# Generated by Django 4.2.6 on 2023-10-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceos', '0003_delete_apple_ceos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apple_ceos',
        ),
    ]
